module.exports = [
  `3Com Corp`,
  `3M Company`,
  `AG Edwards`,
  `Abbott Laboratories`,
  `Abercrombie & Fitch Co`,
  `ABM Industries Incorporated`,
  `ABN AMRO`,
  `Accor`,
  `Ace Hardware Corporation`,
  `Acer`,
  `ACT Manufacturing`,
  `Acterna Corp`,
  `Activision Blizzard`,
  `Acumen`,
  `Adams Resources & Energy`,
  `ADC Telecommunications`,
  `Adelphia Communications Corporation`,
  `Adidas`,
  `Aditi Technologies`,
  `Aditya Birla Group`,
  `Administaff`,
  `Adobe Systems Incorporated`,
  `Adolph Coors Company`,
  `Advance Auto Parts`,
  `Advanced Micro Devices`,
  `AdvancePCS`,
  `Advantica Restaurant Group`,
  `Aetna`,
  `Affiliated Computer Services`,
  `AFLAC Incorporated`,
  `AGCO Corporation`,
  `Agilent Technologies`,
  `Agway`,
  `Ahold Delhaize`,
  `Air France-KLM`,
  `Air Products and Chemicals`,
  `Airborne`,
  `Airbus`,
  `Airgas`,
  `Aitken Spence`,
  `AK Steel Holding Corporation`,
  `AkzoNobel`,
  `Alaska Air Group`,
  `Alberto-Culver Company`,
  `Albertson's`,
  `Alcatel-Lucent`,
  `Alcoa`,
  `Alfa Laval`,
  `Alleghany Corporation`,
  `Allegheny Energy`,
  `Allegheny Technologies Incorporated`,
  `Allergan`,
  `ALLETE`,
  `Alliance Global Group`,
  `Alliant Energy Corporation`,
  `Allianz`,
  `Allied Waste Industries`,
  `Allmerica Financial Corporation`,
  `ALLTEL Corporation`,
  `Alstom`,
  `Altice`,
  `Altria Group`,
  `Amazoncom`,
  `AMC Entertainment`,
  `Amerada Hess Corporation`,
  `AMERCO`,
  `Ameren Corporation`,
  `America West Holdings Corporation`,
  `American Axle & Manufacturing Holdings`,
  `American Eagle Outfitters`,
  `American Electric Power Company`,
  `American Express Company`,
  `American Financial Group`,
  `American Greetings Corporation`,
  `American International Group`,
  `American Power Conversion Corporation`,
  `American Standard Companies`,
  `American Water Works Company`,
  `AmerisourceBergen Corporation`,
  `Ames Department Stores`,
  `Amgen`,
  `Amkor Technology`,
  `AMR Corporation`,
  `AmSouth Bancorp`,
  `Amtran`,
  `Anadarko Petroleum Corporation`,
  `Analog Devices`,
  `Andritz AG`,
  `Anheuser-Busch Companies`,
  `Anixter International`,
  `AnnTaylor`,
  `Anthem`,
  `AOL Time Warner`,
  `Aon`,
  `Aon Corporation`,
  `Apache Corporation`,
  `Apartment Investment and Management Company`,
  `Apollo Tyres`,
  `Apple`,
  `Apple Computer`,
  `Applera Corporation`,
  `Applied Industrial Technologies`,
  `Applied Materials`,
  `Aquila`,
  `ARAMARK Corporation`,
  `Arch Coal`,
  `Archer Daniels Midland Company`,
  `Arcor`,
  `Arkansas Best Corporation`,
  `Armstrong Holdings`,
  `Arrow Electronics`,
  `ArvinMeritor`,
  `Ashland`,
  `Assicurazioni Generali`,
  `Astoria Financial Corporation`,
  `Asus`,
  `AT&T Corp`,
  `Atari`,
  `Atmel Corporation`,
  `Atmos Energy Corporation`,
  `Audiovox Corporation`,
  `Autoliv`,
  `Automatic Data Processing`,
  `AutoNation`,
  `AutoZone`,
  `Avast Software`,
  `Avaya`,
  `Avery Dennison Corporation`,
  `Avianca`,
  `Avista Corporation`,
  `Avnet`,
  `Avon Products`,
  `AXA`,
  `Axiata Group`,
  `Axis Bank Ltd`,
  `Bacardi`,
  `Baker Hughes Incorporated`,
  `Ball Corporation`,
  `Banco Bilbao Vizcaya Argentaria`,
  `Banco Santander`,
  `Bank of America Corporation`,
  `Bank of Kaohsiung`,
  `Bank of Montreal`,
  `Bank One Corporation`,
  `Banknorth Group`,
  `Banta Corporation`,
  `Barclays`,
  `Barilla Group`,
  `Barnes & Noble`,
  `Barrick Gold Corporation`,
  `BASF`,
  `Baskin-Robbins`,
  `Bata`,
  `Bausch & Lomb Incorporated`,
  `Baxter International`,
  `Bayer`,
  `BB&T Corporation`,
  `Beazer Homes USA`,
  `Beckman Coulter`,
  `Becton Dickinson`,
  `Becton, Dickinson and Company`,
  `Bed Bath & Beyond`,
  `Beko`,
  `Belk`,
  `Bell Microproducts`,
  `BellSouth Corporation`,
  `Belo Corp`,
  `Bemis Company`,
  `Benchmark Electronics`,
  `Berkshire Hathaway`,
  `Best Buy Co`,
  `Bethlehem Steel Corporation`,
  `Beverly Enterprises`,
  `Bic`,
  `BIDV`,
  `Big Lots`,
  `Billabong`,
  `BJ Services Company`,
  `BJ's Wholesale Club`,
  `Black & Decker`,
  `Black Hills Corporation`,
  `BMC Software`,
  `BMW`,
  `BNP Paribas`,
  `Boeing`,
  `Boise Cascade Corporation`,
  `Bombardier`,
  `Borders Group`,
  `BorgWarner`,
  `Boston Scientific Corporation`,
  `Bouygues`,
  `Bowater Incorporated`,
  `BRAC`,
  `Bridgestone`,
  `Briggs & Stratton Corporation`,
  `Brightpoint`,
  `Brinker International`,
  `Bristol-Myers Squibb Company`,
  `British Airways`,
  `British Petroleum`,
  `Broadwing`,
  `Brown Shoe Company`,
  `Brown-Forman Corporation`,
  `Brunswick Corporation`,
  `Budget Group`,
  `Burlington Coat Factory Warehouse Corporation`,
  `Burlington Industries`,
  `Burlington Northern Santa Fe Corporation`,
  `Burlington Resources`,
  `BYD`,
  `C H Robinson Worldwide`,
  `Cablevision Systems Corp`,
  `Cabot Corp`,
  `Cadbury Schweppes`,
  `Cadence Design Systems`,
  `Calpine Corp`,
  `Campbell Soup Co`,
  `Canon Inc`,
  `CapGemini`,
  `Capital One`,
  `Capital One Financial Corp`,
  `Cardinal Health`,
  `Caremark Rx`,
  `Caribbean Airlines`,
  `Carlisle Cos`,
  `Carpenter Technology Corp`,
  `Casey's General Stores`,
  `Caterpillar`,
  `CBRL Group`,
  `CDI Corp`,
  `CDW Computer Centers`,
  `Celestica`,
  `CellStar Corp`,
  `Cendant Corp`,
  `Cenex Harvest States Cooperatives`,
  `Centex Corp`,
  `CenturyTel`,
  `Ceridian Corp`,
  `CH2M Hill Cos Ltd`,
  `Champion Enterprises`,
  `Charles Schwab Corp`,
  `Charming Shoppes`,
  `Charter Communications`,
  `Charter One Financial`,
  `Chevron`,
  `ChevronTexaco Corp`,
  `China Merchants Bank`,
  `Chiquita Brands International`,
  `Chubb Corp`,
  `Ciena Corp`,
  `Cigna Corp`,
  `CIMC`,
  `Cincinnati Financial Corp`,
  `Cinergy Corp`,
  `Cintas Corp`,
  `Circuit City Stores`,
  `Cisco Systems`,
  `Citigroup`,
  `Citizens Communications Co`,
  `CKE Restaurants`,
  `Clear Channel Communications`,
  `CMGI`,
  `CMS Energy Corp`,
  `CNF`,
  `Coca-Cola`,
  `Coca-Cola Co`,
  `Coca-Cola Enterprises`,
  `Cognizant Technology Solutions`,
  `Colgate-Palmolive Co`,
  `Collins & Aikman Corp`,
  `Comcast Corp`,
  `Comdisco`,
  `Comerica`,
  `Comfort Systems USA`,
  `Commercial Metals Co`,
  `Community Health Systems`,
  `Compass Bancshares Inc`,
  `Computer Associates International`,
  `Computer Sciences Corp`,
  `Compuware Corp`,
  `Comverse Technology`,
  `ConAgra Foods`,
  `Concentrix`,
  `Concord EFS`,
  `Conectiv`,
  `Conoco Inc`,
  `ConocoPhillips`,
  `Conseco`,
  `Consolidated Edison`,
  `Consolidated Freightways Corp`,
  `Constellation Brands`,
  `Constellation Emergy Group`,
  `Continental Airlines`,
  `Convergys Corp`,
  `Cooper Cameron Corp`,
  `Cooper Industries Ltd`,
  `Cooper Tire & Rubber Co`,
  `Corn Products International`,
  `Corning`,
  `Costco`,
  `Costco Wholesale Corp`,
  `Countrywide Credit Industries`,
  `Coventry Health Care`,
  `Cox Communications`,
  `Crane Co`,
  `Creative Labs`,
  `Crédit Agricole`,
  `Credit Suisse`,
  `Crompton Corp`,
  `Crown Cork & Seal Co`,
  `CSK Auto Corp`,
  `CSX Corp`,
  `Cummins`,
  `CVS Corp`,
  `Cytec Industries`,
  `DR Horton`,
  `D&K Healthcare Resources`,
  `Dabur`,
  `Daikin`,
  `Daimler AG`,
  `Dana Corporation`,
  `Danaher Corporation`,
  `Dangote Group`,
  `Danish Refugee Council`,
  `Danone`,
  `Darden Restaurants`,
  `DaVita`,
  `Dean Foods Company`,
  `Decathlon Group`,
  `Deere & Company`,
  `Del Monte Foods Co`,
  `Dell`,
  `Dell Computer Corporation`,
  `Deloitte`,
  `Delphi Corp`,
  `Delta Air Lines`,
  `Deluxe Corporation`,
  `Deutsche Bank`,
  `Deutsche Telekom`,
  `Devon Energy Corporation`,
  `DHL`,
  `Di Giorgio Corporation`,
  `Dial Corporation`,
  `Diebold Incorporated`,
  `Dillard's`,
  `DIMON Incorporated`,
  `Disney`,
  `Dole Food Company`,
  `Dollar General Corporation`,
  `Dollar Tree Stores`,
  `Dominion Resources`,
  `Domino's Pizza LLC`,
  `Dover Corporation`,
  `Dow Chemical`,
  `Dow Chemical Company`,
  `Dow Jones & Company`,
  `DPL`,
  `DQE`,
  `Dreyer's Grand Ice Cream`,
  `DST Systems`,
  `DTE Energy Co`,
  `Duke Energy Corp`,
  `Dun & Bradstreet`,
  `Dunkin' Donuts`,
  `DURA Automotive Systems`,
  `DynCorp`,
  `Dynegy`,
  `EI Du Pont de Nemours and Company`,
  `EW Scripps Company`,
  `E*Trade Group`,
  `Earthlink`,
  `Eastman Chemical Company`,
  `Eastman Kodak Company`,
  `easyJet`,
  `Eaton Corporation`,
  `Echostar Communications Corporation`,
  `Ecolab`,
  `EDF`,
  `Edison International`,
  `EGL`,
  `El Paso Corporation`,
  `Electrolux`,
  `Electronic Arts`,
  `Electronic Data Systems`,
  `Electronic Data Systems Corp`,
  `Eli Lilly and Company`,
  `Embraer`,
  `EMC Corporation`,
  `Emcor Group`,
  `Emerson Electric`,
  `Emerson Electric Co`,
  `Encompass Services Corporation`,
  `Enel`,
  `Energizer Holdings`,
  `Energy East Corporation`,
  `Engelhard Corporation`,
  `Eni`,
  `Enron Corp`,
  `Entergy Corporation`,
  `Enterprise Products Partners LP`,
  `EOG Resources`,
  `Epson`,
  `Equifax`,
  `Equitable Resources`,
  `Equity Office Properties Trust`,
  `Equity Residential Properties Trust`,
  `Ericsson`,
  `Estee Lauder Companies`,
  `Etisalat`,
  `Eva Air`,
  `Evergreen Marine`,
  `Exelon Corporation`,
  `Exide Technologies`,
  `Expeditors International of Washington`,
  `Express Scripts`,
  `ExxonMobil`,
  `ExxonMobil Corporation`,
  `EY`,
  `Faber-Castell`,
  `Facebook`,
  `Fairchild Semiconductor International`,
  `Family Dollar Stores`,
  `Farmland Industries`,
  `Federal Express Corp`,
  `Federal Mogul Corp`,
  `Federated Department Stores`,
  `FedEx Express`,
  `Felcor Lodging Trust`,
  `Ferrero`,
  `Ferro Corp`,
  `Fiat`,
  `Ficosa`,
  `Fidelity National Financial`,
  `Fifth Third Bancorp`,
  `First American Financial Corp`,
  `First Data Corp`,
  `First National of Nebraska`,
  `First Tennessee National Corp`,
  `FirstEnergy Corp`,
  `FIS (company)`,
  `Fiserv`,
  `Fisher Scientific International`,
  `FleetBoston Financial Co`,
  `Fleetwood Enterprises`,
  `Fleming Companies`,
  `Flowers Foods`,
  `Flowserv Corp`,
  `Fluor Corp`,
  `FMC Corp`,
  `Foamex International Inc`,
  `Foot Locker Inc`,
  `Footstar`,
  `Ford Motor Co`,
  `Ford Motor Company`,
  `Forest Laboratories`,
  `Fortune Brands`,
  `Foster Wheeler Ltd`,
  `FPL Group`,
  `FPT Group`,
  `France Télécom`,
  `Franklin Resources`,
  `Freeport McMoran Copper & Gold`,
  `Frontier Oil Corp`,
  `Fujitsu`,
  `Furniture Brands International`,
  `Gannett Co`,
  `Gap`,
  `Garmin`,
  `Gateway`,
  `GATX Corporation`,
  `Gazprom`,
  `Gemstar-TV Guide International`,
  `GenCorp`,
  `General Cable Corporation`,
  `General Dynamics Corporation`,
  `General Electric`,
  `General Electric Company`,
  `General Mills Inc`,
  `General Motors`,
  `General Motors Corporation`,
  `Generali`,
  `Genesis Health Ventures`,
  `Gentek`,
  `Gentiva Health Services`,
  `Genuine Parts Company`,
  `Genuity`,
  `Genzyme Corporation`,
  `Georgia Gulf Corporation`,
  `Georgia-Pacific Corporation`,
  `Gerdau`,
  `Gillette`,
  `Gillette Company`,
  `Glaxo Smith Kline`,
  `Gold Kist`,
  `Golden State Bancorp`,
  `Golden West Financial Corporation`,
  `Goldman Sachs Group`,
  `Goodrich Corporation`,
  `Goodyear Tire and Rubber Company`,
  `Google`,
  `Granite Construction Incorporated`,
  `Graybar Electric Company`,
  `Great Lakes Chemical Corporation`,
  `Great Plains Energy`,
  `GreenPoint Financial Corp`,
  `Greif Bros Corporation`,
  `Grey Global Group`,
  `Group 1 Automotive`,
  `Guidant Corporation`,
  `HB Fuller Company`,
  `HJ Heinz Company`,
  `H&R Block`,
  `Haier`,
  `Halliburton`,
  `Halliburton Co`,
  `Hankook Tire`,
  `Harley-Davidson`,
  `Harman International Industries`,
  `Harrah's Entertainment`,
  `Harris Corp`,
  `Harsco Corp`,
  `Hartford Financial Services Group`,
  `Hasbro`,
  `Hasee`,
  `Hawaiian Electric Industries`,
  `HCA`,
  `HCL Technologies`,
  `Health Management Associates`,
  `Health Net`,
  `Healthsouth Corp`,
  `Hearst Corporation`,
  `Heineken`,
  `Henry Schein`,
  `Hercules`,
  `Herman Miller`,
  `Hershey Foods Corp`,
  `Hewlett Packard Enterprise`,
  `Hewlett-Packard Company`,
  `Hibernia Corp`,
  `Hillenbrand Industries`,
  `Hilti`,
  `Hilton Hotels Corp`,
  `Hindustan Computers Limited`,
  `Hitachi`,
  `Hollywood Entertainment Corp`,
  `Home Depot`,
  `Hon Industries`,
  `Honda`,
  `Honeywell`,
  `Honeywell International`,
  `Hormel Foods Corp`,
  `Host Marriott Corp`,
  `Household International Corp`,
  `Hovnanian Enterprises`,
  `HP Inc`,
  `HSBC`,
  `HTC`,
  `Huawei`,
  `Hub Group`,
  `Hubbell`,
  `Hughes Supply`,
  `Humana`,
  `Huntington Bancshares`,
  `Hutchison Whampoa Limited`,
  `Hytera`,
  `Hyundai Motor Company`,
  `IBM`,
  `ICAP`,
  `ICICI`,
  `Idacorp`,
  `IDT Corporation`,
  `IKEA`,
  `IKON Office Solutions`,
  `Illinois Tool Works`,
  `IMC Global`,
  `Imperial Sugar Company`,
  `IMS Health`,
  `Indesit`,
  `Indofood`,
  `Infosys`,
  `ING Group`,
  `Ingersoll Rand`,
  `Ingles Market Inc`,
  `Ingram Micro`,
  `Insight Enterprises`,
  `Instagram`,
  `Integrated Electrical Services`,
  `Intel Corporation`,
  `International Business Machines Corp`,
  `International Flavors & Fragrances`,
  `International Multifoods Corporation`,
  `International Paper Co`,
  `Interpublic Group of Companies`,
  `Interstate Bakeries Corporation`,
  `Intesa Sanpaolo`,
  `Intuit`,
  `Isuzu`,
  `IT Group`,
  `ITT Industries`,
  `Ivax Corp`,
  `JB Hunt Transport Services`,
  `JC Penny Co`,
  `JP Morgan Chase & Co`,
  `Jabil Circuit`,
  `Jack In The Box`,
  `Jacobs Engineering Group`,
  `Jardine Matheson`,
  `JDS Uniphase Corp`,
  `Jefferson-Pilot Co`,
  `JG Summit Holdings`,
  `Jimmy Choo`,
  `John Hancock Financial Services`,
  `Johnson & Johnson`,
  `Johnson Controls`,
  `Jollibee`,
  `Jones Apparel Group`,
  `JPMorgan Chase & Co`,
  `JXD`,
  `K-Mart Corp`,
  `KB Home`,
  `Kellogg Company`,
  `Kellwood Company`,
  `Kelly Services`,
  `Kemet Corp`,
  `Kennametal`,
  `Kenya Airways`,
  `Kerr-McGee Corporation`,
  `KeyCorp`,
  `KeySpan Corp`,
  `KFC`,
  `Kia Motors`,
  `Kimball International`,
  `Kimberly-Clark Corporation`,
  `Kindred Healthcare`,
  `Kingston Technology`,
  `KLA-Tencor Corporation`,
  `Knight-Ridder`,
  `Knorr`,
  `Kohl's Corp`,
  `Komatsu Limited`,
  `Konami`,
  `KPMG`,
  `KPMG Consulting`,
  `Krispy Kreme`,
  `Kroger Co`,
  `L-3 Communications Holdings`,
  `L'Oréal`,
  `La-Z-Boy`,
  `Laboratory Corporation of America Holdings`,
  `Lactalis`,
  `Lagardère`,
  `Lam Research Corporation`,
  `LandAmerica Financial Group`,
  `Lands' End`,
  `Landstar System`,
  `Lear`,
  `Lear Corporation`,
  `Legg Mason`,
  `Leggett & Platt`,
  `Lehman Brothers Holdings`,
  `Lennar Corporation`,
  `Lennox International`,
  `Lenovo`,
  `Leonardo`,
  `Leoni AG`,
  `Level 3 Communications`,
  `Levi Strauss & Co`,
  `Lexmark`,
  `Lexmark International`,
  `LG`,
  `LG Electronics`,
  `Limited`,
  `Lincoln National Corporation`,
  `Linde`,
  `Linens 'n Things`,
  `Lithia Motors`,
  `LiuGong`,
  `Liz Claiborne`,
  `Lockheed Martin`,
  `Lockheed Martin Corporation`,
  `Loews Corporation`,
  `Longs Drug Stores Corporation`,
  `Lotte Group`,
  `Louisiana-Pacific Corporation`,
  `Lowe's Companies`,
  `LSI Logic Corporation`,
  `Lucent Technologies`,
  `Lukoil`,
  `Lupin`,
  `Luxgen`,
  `Luxottica`,
  `Lyondell Chemical Company`,
  `M & T Bank Corporation`,
  `MDC Holdings`,
  `Magellan Health Services`,
  `Maggi`,
  `Mail-Well`,
  `Mandalay Resort Group`,
  `Manor Care`,
  `Manpower`,
  `Marathon Oil Corporation`,
  `Mariner Health Care`,
  `Markel Corporation`,
  `Marriott`,
  `Marriott International`,
  `Marsh & McLennan Companies`,
  `Marsh Supermarkets`,
  `Marshall & Ilsley Corporation`,
  `Martin Marietta Materials`,
  `Martini & Rossi`,
  `Masco Corporation`,
  `Massey Energy Company`,
  `MasTec`,
  `Masterfoods`,
  `Mattel`,
  `Maxim Integrated Products`,
  `Maxtor Corporation`,
  `Maxxam`,
  `Maxxis`,
  `Maytag Corporation`,
  `MBNA Corporation`,
  `McCormick & Company Incorporated`,
  `McDonald's`,
  `McDonald's Corporation`,
  `McKesson Corporation`,
  `McLeodUSA Incorporated`,
  `MDU Resources Group`,
  `MeadWestvaco Corporation`,
  `Medtronic`,
  `Mellon Financial Corporation`,
  `Mercedes-AMG`,
  `Mercedes-Benz`,
  `Merck & Co`,
  `Mercury General Corporation`,
  `Merrill Lynch & Co`,
  `Metaldyne Corporation`,
  `Metals USA`,
  `MetLife`,
  `Metris Companies Inc`,
  `MGIC Investment Corporation`,
  `MGM Mirage`,
  `Michaels Stores`,
  `Michelin`,
  `Micro-Star International`,
  `Micron Technology`,
  `Microsoft`,
  `Microsoft Corporation`,
  `Microsoft Mobile`,
  `Milacron`,
  `Millennium Chemicals`,
  `Millipore Corporation`,
  `Mirant Corporation`,
  `Mitsubishi Electric`,
  `Mobil`,
  `Mohawk Industries`,
  `Molex Incorporated`,
  `Monsanto Company`,
  `Morgan Stanley Dean Witter & Co`,
  `Motorola`,
  `MPS Group`,
  `Murphy Oil Corporation`,
  `Nabors Industries Inc`,
  `Nacco Industries Inc`,
  `Nagarro`,
  `Namco Bandai Games`,
  `Namco Bandai Holdings`,
  `Nash Finch Company`,
  `National City Corp`,
  `National Commerce Financial Corporation`,
  `National Fuel Gas Company`,
  `National Oilwell Inc`,
  `National Rural Utilities Cooperative Finance Corporation`,
  `National Semiconductor Corporation`,
  `National Service Industries Inc`,
  `Navistar International Corporation`,
  `NCR Corporation`,
  `Nestlé`,
  `NetApp`,
  `New Jersey Resources Corporation`,
  `New York Times Company`,
  `Newell Rubbermaid Inc`,
  `Newmont Mining Corporation`,
  `News Corporation`,
  `Nextel Communications Inc`,
  `Nicor Inc`,
  `Nike Inc`,
  `Nike`,
  `Nikon`,
  `Nintendo`,
  `NiSource Inc`,
  `Nissan`,
  `Noble Energy Inc`,
  `Nokia`,
  `Nordstrom Inc`,
  `Norfolk Southern Corporation`,
  `Nortek Inc`,
  `North Fork Bancorporation Inc`,
  `Northeast Utilities System`,
  `Northern Trust Corporation`,
  `Northrop Grumman Corporation`,
  `Northwest Airlines Corp`,
  `NorthWestern Corporation`,
  `Novartis`,
  `Novellus Systems Inc`,
  `NSTAR`,
  `NTL Incorporated`,
  `Nucor Corp`,
  `Nvidia Corp`,
  `NVR Inc`,
  `Occidental Petroleum Corp`,
  `Ocean Energy Inc`,
  `Office Depot`,
  `OfficeMax Inc`,
  `OGE Energy Corp`,
  `Oglethorpe Power Corp`,
  `Ohio Casualty Corp`,
  `Oknoplast`,
  `Old Republic International Corp`,
  `Olin Corp`,
  `OM Group Inc`,
  `Omnicare Inc`,
  `Omnicom Group`,
  `On Semiconductor Corp`,
  `ONEOK Inc`,
  `Ooredoo`,
  `Oracle Corp`,
  `Oracle Corporation`,
  `Oshkosh Truck Corp`,
  `Outback Steakhouse`,
  `Owens & Minor`,
  `Owens Corning`,
  `Owens-Illinois Inc`,
  `Oxford Health Plans Inc`,
  `Paccar Inc`,
  `Pacific Gas & Electric Corp`,
  `PacifiCare Health Systems Inc`,
  `Packaging Corp of America`,
  `Pactiv Corp`,
  `Pall Corp`,
  `Panasonic Corporation`,
  `Pantry Inc`,
  `Park Place Entertainment Corp`,
  `Parker Hannifin Corp`,
  `Parmalat`,
  `Partners In Health`,
  `Pathmark Stores`,
  `Paychex Inc`,
  `Payless Shoesource Inc`,
  `Penn Traffic Co`,
  `Pennzoil-Quaker State Company`,
  `Pentair Inc`,
  `Peoples Energy Corp`,
  `PeopleSoft Inc`,
  `Pep Boys Manny, Moe & Jack`,
  `Pepper Lunch`,
  `Pepsi Bottling Group`,
  `PepsiAmericas`,
  `PepsiCo`,
  `Performance Food Group Co`,
  `Perini Corp`,
  `PerkinElmer Inc`,
  `Perot Systems Corp`,
  `Petco Animal Supplies`,
  `Peter Kiewit Sons'`,
  `Petronas`,
  `Petrovietnam`,
  `PETsMART Inc`,
  `Pfizer`,
  `Pfizer Inc`,
  `Phar Mor`,
  `Pharmacia Corp`,
  `Phelps Dodge Corp`,
  `Philip Morris Companies`,
  `Philips`,
  `Phillips Petroleum Co`,
  `Phillips Van Heusen Corp`,
  `Phoenix Companies Inc`,
  `Pier 1 Imports`,
  `Pilgrim's Pride Corporation`,
  `Ping An Bank`,
  `Ping An Insurance`,
  `Pinnacle West Capital Corp`,
  `Pioneer-Standard Electronics`,
  `Pirelli`,
  `Pitney Bowes`,
  `Pittston Brinks Group`,
  `Pladis`,
  `Plains All American Pipeline LP`,
  `PNC Financial Services Group`,
  `PNM Resources Inc`,
  `Polaris Industries`,
  `Polo Ralph Lauren Corp`,
  `PolyOne Corp`,
  `Popular Inc`,
  `POSCO`,
  `Potlatch Corp`,
  `Potomac Electric Power Co`,
  `PPG Industries Inc`,
  `PPL Corp`,
  `Praxair Inc`,
  `Precision Castparts Corp`,
  `Premcor`,
  `Pride International Inc`,
  `Primedia Inc`,
  `Principal Financial Group`,
  `Pro-Fac Cooperative`,
  `Procter & Gamble`,
  `Procter & Gamble Co`,
  `Progress Energy Inc`,
  `Progressive Corporation`,
  `Protective Life Corp`,
  `Proton`,
  `Provident Financial Group`,
  `Providian Financial Corp`,
  `Prudential Financial`,
  `PSA Peugeot Citroën`,
  `PSS World Medical Inc`,
  `Public Service Enterprise Group`,
  `Publix Super Markets`,
  `Puget Energy`,
  `Pulte Homes Inc`,
  `PwC`,
  `QNB Group`,
  `Qualcomm Inc`,
  `Quanta Services`,
  `Quantum Corp`,
  `Quest Diagnostics`,
  `Questar Corp`,
  `Quintiles Transnational`,
  `Qwest Communications Intl Inc`,
  `RJ Reynolds Tobacco Company`,
  `RR Donnelley & Sons Company`,
  `Radio Shack Corporation`,
  `Ranbaxy`,
  `Raymond James Financial`,
  `Raytheon Company`,
  `Reader's Digest Association`,
  `Reckitt Benckiser`,
  `Red Bull`,
  `Red Bus`,
  `Reebok International Ltd`,
  `Regions Financial Corp`,
  `Regis Corporation`,
  `Regus`,
  `Reliance Steel & Aluminum Co`,
  `Reliant Energy`,
  `Renault`,
  `Rent A Center Inc`,
  `Repsol`,
  `Republic Services Inc`,
  `Revlon Inc`,
  `RGS Energy Group Inc`,
  `Ricoh`,
  `Rite Aid Corp`,
  `Riverwood Holding`,
  `RoadwayCorp`,
  `Robert Bosch GmbH`,
  `Robert Half International`,
  `Rock-Tenn Co`,
  `Rockstar Energy`,
  `Rockwell Automation Inc`,
  `Rockwell Collins Inc`,
  `Rohde & Schwarz`,
  `Rohm & Haas Co`,
  `Ross Stores Inc`,
  `Royal Bank of Canada`,
  `Royal Bank of Scotland`,
  `Royal Dutch Shell`,
  `RPG Group`,
  `RPM`,
  `Ruddick Corp`,
  `Rusal`,
  `Ryder System Inc`,
  `Ryerson Tull Inc`,
  `Ryland Group`,
  `SABMiller plc`,
  `Sabre Holdings Corp`,
  `Safeco Corp`,
  `Safeguard Scientifics`,
  `Safeway Inc`,
  `Saks Inc`,
  `Samsung Electronics`,
  `San Miguel Corporation`,
  `SanDisk`,
  `Sanmina-SCI Inc`,
  `Sanofi Aventis`,
  `SAP SE`,
  `Sapient Corporation`,
  `Sara Lee Corp`,
  `SAS`,
  `Sasken Communication Technologies Limited`,
  `Sasol`,
  `SBC Communications Inc`,
  `Scana Corp`,
  `Schering-Plough Corp`,
  `Schlumberger`,
  `Schneider Electric`,
  `Scholastic Corp`,
  `SCI Systems Onc`,
  `Science Applications Intl`,
  `Scientific-Atlanta Inc`,
  `Scotiabank`,
  `Scotts Company`,
  `Seaboard Corp`,
  `Sealed Air Corp`,
  `Sears`,
  `Sears Roebuck & Co`,
  `Sega Sammy Holdings`,
  `Sempra Energy`,
  `Sequa Corp`,
  `Servcorp`,
  `Service Corp International`,
  `ServiceMaster Co`,
  `Shaw Group Inc`,
  `Shenzhen Airlines`,
  `Sherwin-Williams Company`,
  `Shopko Stores Inc`,
  `Siebel Systems Inc`,
  `Siemens`,
  `Sierra Health Services Inc`,
  `Sierra Pacific Resources`,
  `Silgan Holdings`,
  `Silicon Graphics Inc`,
  `Simon Property Group Inc`,
  `Singapore Airlines`,
  `Sinopec`,
  `SLM Corporation`,
  `SM Investments Corporation`,
  `Smith International Inc`,
  `Smithfield Foods Inc`,
  `Smurfit-Stone Container Corp`,
  `Snap-On Inc`,
  `Société Générale`,
  `Solaris Bus & Coach`,
  `Solectron Corp`,
  `Solutia Inc`,
  `Sonic Automotive`,
  `Sonoco Products Co`,
  `Sony`,
  `Sony Computer Entertainment`,
  `Sony Music Entertainment`,
  `Sony Pictures Entertainment`,
  `Southern Company`,
  `Southern Union Company`,
  `SouthTrust Corp`,
  `Southwest Airlines`,
  `Southwest Airlines Co`,
  `Southwest Gas Corp`,
  `Sovereign Bancorp`,
  `Spartan Stores Inc`,
  `Spherion Corp`,
  `Sports Authority Inc`,
  `Sprint Corp`,
  `SPX Corp`,
  `Square Enix`,
  `St Jude Medical Inc`,
  `St Paul Cos`,
  `Staff Leasing`,
  `StanCorp Financial Group Inc`,
  `Standard Chartered`,
  `Standard Pacific Corp`,
  `Stanley Works`,
  `Staples Inc`,
  `Starbucks`,
  `Starbucks Corp`,
  `Starwood Hotels & Resorts Worldwide Inc`,
  `State Street Corp`,
  `Stater Bros Holdings`,
  `Steelcase Inc`,
  `Stein Mart Inc`,
  `Stewart & Stevenson Services Inc`,
  `Stewart Information Services Corp`,
  `Stilwell Financial Inc`,
  `Storage Technology Corporation`,
  `Stryker Corp`,
  `Sun Healthcare Group`,
  `Sun Microsystems`,
  `SunGard Data Systems`,
  `Sunoco`,
  `SunTrust Banks Inc`,
  `Supervalu Inc`,
  `Swift Transportation, Co`,
  `Symbol Technologies Inc`,
  `Synovus Financial Corp`,
  `Sysco Corp`,
  `Systemax`,
  `Tagged`,
  `Taiwan Beer`,
  `Target Corp`,
  `Tata Motors`,
  `Tate & Lyle`,
  `TCL Corporation`,
  `TCS`,
  `Tech Data Corporation`,
  `Tech Mahindra`,
  `TECO Energy Inc`,
  `Tecumseh Products Company`,
  `Tektronix Inc`,
  `Teleflex Incorporated`,
  `Telefonica`,
  `Telephone & Data Systems Inc`,
  `Tellabs`,
  `Temple-Inland Inc`,
  `Tencent`,
  `Tenet Healthcare Corporation`,
  `Tenneco Automotive`,
  `Teradyne Inc`,
  `Terex Corp`,
  `Tesco`,
  `Tesoro Petroleum Corp`,
  `Tetra Pak`,
  `Texas Industries`,
  `Texas Instruments Incorporated`,
  `Textron Inc`,
  `The AES Corporation`,
  `The Allstate Corporation`,
  `The Alpine Group`,
  `The Bank of New York Company`,
  `The Bear Stearns Companies`,
  `The Black & Decker Corporation`,
  `The Boeing Company`,
  `The Clorox Co`,
  `The Coffee Bean & Tea Leaf`,
  `The Goodyear Tire & Rubber Company`,
  `The International Press and Media Group (also known as "IPMG")`,
  `The LTV Corporation`,
  `The Lubrizol Corporation`,
  `The May Department Stores Company`,
  `The McGraw-Hill Companies`,
  `The Men's Wearhouse`,
  `The MONY Group`,
  `The Neiman Marcus Group`,
  `Thermo Electron Corporation`,
  `Thomas & Betts Corporation`,
  `Thomson Reuters`,
  `Tiffany & Co`,
  `Timken Company`,
  `Tissot`,
  `TJX Companies Inc`,
  `TMP Worldwide Inc`,
  `Toll Brothers Inc`,
  `Torchmark Corporation`,
  `Toro Company`,
  `Toshiba`,
  `Total SA`,
  `Tower Automotive`,
  `Towers Watson`,
  `Toyota`,
  `Toys 'R' Us Inc`,
  `Trans World Entertainment Corp`,
  `TransMontaigne Inc`,
  `Transocean Inc`,
  `TravelCenters of America`,
  `Trend Micro`,
  `Triad Hospitals Inc`,
  `Tribune Company`,
  `Trigon Healthcare`,
  `Trinity Industries Inc`,
  `Trump Hotels & Casino Resorts`,
  `TruServ Corporation`,
  `TRW Automotive`,
  `TRW Inc`,
  `TSMC`,
  `TXU Corp`,
  `Tyco`,
  `Tyson Foods Inc`,
  `US Bancorp`,
  `US Industries`,
  `UAL Corporation`,
  `Uber`,
  `UGI Corporation`,
  `Ülker`,
  `Unicredit`,
  `Unified Western Grocers Inc`,
  `Unilever`,
  `Union Pacific Corporation`,
  `Union Planters Corp`,
  `Unisource Energy Corp`,
  `Unisys`,
  `Unisys Corporation`,
  `United Airlines`,
  `United Auto Group Inc`,
  `United Defense Industries`,
  `United Parcel Service Inc`,
  `United Rentals Inc`,
  `United Stationers Inc`,
  `United Technologies Corporation`,
  `UnitedHealth Group Incorporated`,
  `Unitrin Inc`,
  `Universal Corporation`,
  `Universal Forest Products Inc`,
  `Universal Health Services Inc`,
  `Unocal Corporation`,
  `Unova Inc`,
  `UnumProvident Corporation`,
  `URS Corporation`,
  `US Airways Group Inc`,
  `US Oncology Inc`,
  `USA Interactive`,
  `USFreighways Corporation`,
  `USG Corporation`,
  `UST Inc`,
  `Valero Energy Corporation`,
  `Valspar Corporation`,
  `Value City Department Stores Inc`,
  `Vanke`,
  `Varco International Inc`,
  `Vectren Corporation`,
  `Veritas Software Corporation`,
  `Verizon Communications Inc`,
  `Vestel`,
  `VF Corporation`,
  `Viacom Inc`,
  `Viad Corp`,
  `Viasystems Group Inc`,
  `Viettel Mobile`,
  `Vimpelcom`,
  `Virgin Group`,
  `Vishay Intertechnology Inc`,
  `Visteon Corporation`,
  `Vizio`,
  `VNPT`,
  `Vodafone`,
  `Voith`,
  `Volt Information Sciences Inc`,
  `Vulcan Materials Company`,
  `WR Berkley Corporation`,
  `WR Grace & Co`,
  `WW Grainger Inc`,
  `Wachovia Corporation`,
  `Wakenhut Corporation`,
  `Wal-Mart`,
  `Wal-Mart Stores Inc`,
  `Walgreen Co`,
  `Wallace Computer Services Inc`,
  `Walt Disney Co`,
  `Walter Industries Inc`,
  `Washington Mutual Inc`,
  `Washington Post Co`,
  `Waste Management Inc`,
  `Watsco Inc`,
  `Weatherford International Inc`,
  `Weis Markets`,
  `Wellpoint Health Networks Inc`,
  `Wells Fargo & Company`,
  `Wendy's International Inc`,
  `Werner Enterprises Inc`,
  `WESCO International Inc`,
  `Western Digital Inc`,
  `Western Gas Resources Inc`,
  `WestPoint Stevens Inc`,
  `Weyerhauser Company`,
  `WGL Holdings Inc`,
  `Whirlpool Corporation`,
  `Whole Foods Market Inc`,
  `Wikimedia Foundation`,
  `Willamette Industries`,
  `Williams Companies Inc`,
  `Williams Sonoma Inc`,
  `Winn Dixie Stores Inc`,
  `Wipro`,
  `Wirecard`,
  `Wisconsin Energy Corporation`,
  `Wm Wrigley Jr Company`,
  `World Fuel Services Corporation`,
  `WorldCom Inc`,
  `Worthington Industries Inc`,
  `WPS Resources Corporation`,
  `Wyeth`,
  `Wyndham International Inc`,
  `Xcel Energy Inc`,
  `Xerox Corp`,
  `Xilinx Inc`,
  `XO Communications Inc`,
  `Yahoo`,
  `Yakult`,
  `Yamaha Corporation`,
  `Yamaha Motor Company`,
  `Yellow Corporation`,
  `York International Corp`,
  `Yum Brands`,
  `Zale Corporation`,
  `Zensar Technologies`,
  `Zhujiang Beer`,
  `Zions Bancorporation`,
  `ZTE`
];